name: continuous integration

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  msys2:
    runs-on: windows-2019
    steps:
      - name: check out Freeciv
        uses: actions/checkout@v2
      - name: install dependencies
        # A mapping from msys2/setup-msys2 version to msys2 version can be
        # found at
        # https://github.com/msys2/setup-msys2/blob/master/CHANGELOG.md
        # 2.1.2 provides msys2 snapshot 20201109
        uses: msys2/setup-msys2@v2.1.2
        with:
          install: >
            make
            gettext
            pkg-config
            git
            automake
            libtool
            autoconf
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-icu
            mingw-w64-x86_64-curl
            mingw-w64-x86_64-bzip2
            mingw-w64-x86_64-readline
            mingw-w64-x86_64-imagemagick
            mingw-w64-x86_64-SDL2_mixer
            mingw-w64-x86_64-drmingw
            mingw-w64-x86_64-tolua
            mingw-w64-x86_64-gtk3
            mingw-w64-x86_64-qt5
            mingw-w64-x86_64-SDL2_image
            mingw-w64-x86_64-SDL2_ttf
            mingw-w64-x86_64-SDL2_gfx
            mingw-w64-x86_64-nsis
      - name: build
        shell: msys2 {0}
        run: |
          cd windows/installer_msys2
          make ci
  os_x:
    runs-on: macos-10.15
    steps:
      - name: check out Freeciv
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
          brew install \
            lua@5.4 \
            autoconf \
            automake \
            gettext \
            libtool \
            pkg-config \
            atk \
            freetype \
            gettext \
            glib \
            gtk+3 \
            icu4c \
            pango \
            sdl2_gfx \
            sdl2_image \
            sdl2_mixer \
            sdl2_ttf \
            qt
      - name: build
        shell: bash
        run: ./scripts/ci-build.sh os_x
  normal:
    runs-on: ubuntu-20.04
    steps:
      - name: check out Freeciv
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -y install \
            gettext \
            libgtk-3-dev \
            libcurl4-openssl-dev \
            libtool \
            automake \
            autoconf \
            autotools-dev \
            language-pack-en \
            python3.7 \
            liblzma-dev \
            libicu-dev \
            libsqlite3-dev \
            qt5-default \
            libsdl2-mixer-dev \
            libsdl2-gfx-dev \
            libsdl2-image-dev \
            libsdl2-ttf-dev \
            libmysqlclient-dev
      - name: build
        shell: bash
        run: ./scripts/ci-build.sh normal
  dist:
    runs-on: ubuntu-20.04
    steps:
      - name: check out Freeciv
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -y install \
            libtolua-dev \
            gettext \
            libcurl4-openssl-dev \
            libtool \
            automake \
            autoconf \
            autotools-dev \
            python3.7 \
            liblzma-dev \
            libicu-dev \
            libsqlite3-dev
      - name: build
        shell: bash
        run: ./scripts/ci-build.sh dist
  meson:
    runs-on: ubuntu-20.04
    steps:
      - name: check out Freeciv
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -y install \
            meson \
            libtolua-dev \
            gettext \
            libgtk-3-dev \
            libcurl4-openssl-dev \
            libtool \
            automake \
            autoconf \
            autotools-dev \
            language-pack-en \
            python3.7 \
            liblzma-dev \
            libicu-dev \
            libsqlite3-dev \
            qt5-default \
            libsdl2-mixer-dev \
            libsdl2-gfx-dev \
            libsdl2-image-dev \
            libsdl2-ttf-dev \
            libmysqlclient-dev
      - name: build
        shell: bash
        run: ./scripts/ci-build.sh meson
  clang_debug:
    runs-on: ubuntu-20.04
    steps:
      - name: check out Freeciv
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo add-apt-repository ppa:kvilhaugsvik/backports
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -y install \
            clang \
            libtolua-dev \
            liblua5.4-dev \
            gettext \
            libgtk-3-dev \
            libcurl4-openssl-dev \
            libtool \
            automake \
            autoconf \
            autotools-dev \
            language-pack-en \
            python3.7 \
            liblzma-dev \
            libicu-dev \
            libsqlite3-dev \
            qt5-default \
            libsdl2-mixer-dev \
            libsdl2-gfx-dev \
            libsdl2-image-dev \
            libsdl2-ttf-dev \
            libmysqlclient-dev
      - name: build
        shell: bash
        run: ./scripts/ci-build.sh clang_debug
