name: continuous integration

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  msys2:
    runs-on: windows-2022
    steps:
      - name: check out Freeciv
        uses: actions/checkout@v4.1.7
      - name: install dependencies
        # A mapping from msys2/setup-msys2 version to msys2 version can be
        # found at
        # https://github.com/msys2/setup-msys2/blob/main/CHANGELOG.md
        # 2.24.1 provides msys2 snapshot 20240727
        uses: msys2/setup-msys2@v2.24.1
        with:
          msystem: UCRT64
          install: >
            make
            gettext
            git
            mingw-w64-ucrt-x86_64-7zip
            mingw-w64-ucrt-x86_64-meson
            mingw-w64-ucrt-x86_64-pkgconf
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-icu
            mingw-w64-ucrt-x86_64-curl
            mingw-w64-ucrt-x86_64-bzip2
            mingw-w64-ucrt-x86_64-readline
            mingw-w64-ucrt-x86_64-imagemagick
            mingw-w64-ucrt-x86_64-SDL2_mixer
            mingw-w64-ucrt-x86_64-drmingw
            mingw-w64-ucrt-x86_64-tolua
            mingw-w64-ucrt-x86_64-gtk3
            mingw-w64-ucrt-x86_64-gtk4
            mingw-w64-ucrt-x86_64-qt6-base
            mingw-w64-ucrt-x86_64-qt6-svg
            mingw-w64-ucrt-x86_64-SDL2_image
            mingw-w64-ucrt-x86_64-SDL2_ttf
            mingw-w64-ucrt-x86_64-SDL2_gfx
            mingw-w64-ucrt-x86_64-nsis
      - name: build
        shell: msys2 {0}
        run: |
          cd windows/installer_msys2
          make -f Makefile.meson ci
  os_x:
    runs-on: macos-13
    steps:
      - name: check out Freeciv
        uses: actions/checkout@v4.1.1
      - name: install dependencies
        run: |
          # Remove symlinks of the old python version
          rm /usr/local/bin/2to3*
          rm /usr/local/bin/idle3*
          rm /usr/local/bin/pydoc3*
          rm /usr/local/bin/python3*
          brew install \
            llvm \
            lua@5.4 \
            autoconf \
            automake \
            gettext \
            libtool \
            pkg-config \
            atk \
            freetype \
            gettext \
            glib \
            jpeg \
            gtk+3 \
            gtk4 \
            icu4c \
            pango \
            sdl2_gfx \
            sdl2_image \
            sdl2_mixer \
            sdl2_ttf \
            qt@6 \
            mysql-client \
            postgresql \
            unixodbc
      - name: build
        shell: bash
        run: ./scripts/ci-build.sh os_x
  mac-meson:
    runs-on: macos-14
    steps:
      - name: check out Freeciv
        uses: actions/checkout@v4.1.7
      - name: install dependencies
        run: |
          # Remove symlinks of the old python version
          rm /usr/local/bin/2to3*
          rm /usr/local/bin/idle3*
          rm /usr/local/bin/pydoc3*
          rm /usr/local/bin/python3*
          brew install \
            pkg-config \
            meson \
            lua@5.4 \
            jpeg \
            gtk+3 \
            gtk4 \
            sdl2_mixer \
            sdl2_image \
            sdl2_ttf \
            qt@6
      - name: build
        shell: bash
        run: ./scripts/ci-build.sh mac-meson
  normal:
    runs-on: ubuntu-24.04
    steps:
      - name: check out Freeciv
        uses: actions/checkout@v4.1.7
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -y install \
            gettext \
            libgtk-3-dev \
            libgtk-4-dev \
            libcurl4-openssl-dev \
            libtool \
            automake \
            autoconf \
            autotools-dev \
            language-pack-en \
            python3.10 \
            liblzma-dev \
            libicu-dev \
            libsqlite3-dev \
            qt6-base-dev \
            libsdl2-mixer-dev \
            libsdl2-gfx-dev \
            libsdl2-image-dev \
            libsdl2-ttf-dev \
            libmysqlclient-dev \
            unixodbc-dev
      - name: build
        shell: bash
        run: ./scripts/ci-build.sh normal
  dist:
    runs-on: ubuntu-24.04
    steps:
      - name: check out Freeciv
        uses: actions/checkout@v4.1.7
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -y install \
            libtolua-dev \
            zip \
            gettext \
            libcurl4-openssl-dev \
            libtool \
            automake \
            autoconf \
            autotools-dev \
            python3.10 \
            liblzma-dev \
            libicu-dev \
            libsqlite3-dev \
            libgtk-3-dev \
            qt6-base-dev \
            libsdl2-mixer-dev \
            libsdl2-gfx-dev \
            libsdl2-image-dev \
            libsdl2-ttf-dev \
            libmysqlclient-dev
      - name: build
        shell: bash
        run: ./scripts/ci-build.sh dist
  meson:
    runs-on: ubuntu-24.04
    steps:
      - name: check out Freeciv
        uses: actions/checkout@v4.1.7
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -y install \
            meson \
            libtolua-dev \
            gettext \
            libgtk-3-dev \
            libgtk-4-dev \
            libcurl4-openssl-dev \
            libtool \
            automake \
            autoconf \
            autotools-dev \
            language-pack-en \
            python3.10 \
            liblzma-dev \
            libicu-dev \
            libsqlite3-dev \
            qt6-base-dev \
            libsdl2-mixer-dev \
            libsdl2-gfx-dev \
            libsdl2-image-dev \
            libsdl2-ttf-dev \
            libmysqlclient-dev
      - name: build
        shell: bash
        run: ./scripts/ci-build.sh meson
  clang_debug:
    runs-on: ubuntu-24.04
    steps:
      - name: check out Freeciv
        uses: actions/checkout@v4.1.7
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -y install \
            clang \
            libtolua-dev \
            liblua5.4-dev \
            gettext \
            libgtk-3-dev \
            libgtk-4-dev \
            libcurl4-openssl-dev \
            libtool \
            automake \
            autoconf \
            autotools-dev \
            language-pack-en \
            python3.10 \
            liblzma-dev \
            libicu-dev \
            libsqlite3-dev \
            qt6-base-dev \
            libsdl2-mixer-dev \
            libsdl2-gfx-dev \
            libsdl2-image-dev \
            libsdl2-ttf-dev \
            libmysqlclient-dev \
            unixodbc-dev
      - name: build
        shell: bash
        run: ./scripts/ci-build.sh clang_debug
  tcc:
    runs-on: ubuntu-24.04
    steps:
      - name: check out Freeciv
        uses: actions/checkout@v4.1.7
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -y install \
            tcc \
            gettext \
            libgtk-3-dev \
            libgtk-4-dev \
            libcurl4-openssl-dev \
            libtool \
            automake \
            autoconf \
            autotools-dev \
            language-pack-en \
            python3.10 \
            liblzma-dev \
            libicu-dev \
            libsqlite3-dev \
            libmysqlclient-dev \
            unixodbc-dev
      - name: build
        shell: bash
        run: ./scripts/ci-build.sh tcc

  emsdk:
    runs-on: ubuntu-24.04
    steps:
      - name: check out Freeciv
        uses: actions/checkout@v4.1.7
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -y install \
            meson \
            libtolua-dev
      - name: build
        shell: bash
        run: ./scripts/ci-build.sh emsdk
